{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lastro.fullname" . }}-data
  labels:
    {{- include "lastro.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClassName }}
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if .Values.persistence.uploads.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lastro.fullname" . }}-uploads
  labels:
    {{- include "lastro.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.uploads.accessMode }}
  {{- if .Values.persistence.uploads.storageClassName }}
  storageClassName: {{ .Values.persistence.uploads.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
{{- end }}
