-- Native Postgres equivalent of the SQLite table-rebuild this migration performs (see
-- REBUILD_OVERRIDES in scripts/postgres/generate-schema.mjs).
ALTER TABLE users DROP CONSTRAINT users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('investidor','cedente','sacado','admin','seguradora'));
ALTER TABLE users ADD COLUMN insurer_key TEXT;

ALTER TABLE duplicatas ADD COLUMN sinistro_status TEXT NOT NULL DEFAULT 'none';
ALTER TABLE duplicatas ADD COLUMN sinistro_note TEXT;

CREATE TABLE IF NOT EXISTS api_keys (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  key_hash TEXT NOT NULL UNIQUE,
  key_prefix TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT 'Chave de produção',
  revoked INTEGER NOT NULL DEFAULT 0,
  last_used_at TEXT,
  created_at TEXT NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS webhooks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  url TEXT NOT NULL,
  event TEXT NOT NULL,
  secret TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_api_keys_user ON api_keys(user_id);
CREATE INDEX IF NOT EXISTS idx_webhooks_user_event ON webhooks(user_id, event);
