CREATE TABLE IF NOT EXISTS guarantee_fund_tranche_ledger (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classe TEXT NOT NULL CHECK(classe IN ('senior', 'junior')),
  tipo TEXT NOT NULL CHECK(tipo IN ('aporte', 'resgate', 'rendimento', 'perda_absorvida')),
  valor REAL NOT NULL,
  descricao TEXT NOT NULL,
  investor_id INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_guarantee_fund_tranche_ledger_classe ON guarantee_fund_tranche_ledger(classe);
CREATE INDEX IF NOT EXISTS idx_guarantee_fund_tranche_ledger_investor ON guarantee_fund_tranche_ledger(investor_id);

CREATE TABLE IF NOT EXISTS guarantee_fund_tranche_quota_movements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  investor_id INTEGER NOT NULL REFERENCES users(id),
  classe TEXT NOT NULL CHECK(classe IN ('senior', 'junior')),
  quotas REAL NOT NULL,
  cota_price REAL NOT NULL,
  created_at TEXT NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_guarantee_fund_tranche_quota_movements_investor ON guarantee_fund_tranche_quota_movements(investor_id, classe);
