-- Feature "AI CFO fica atrás de Pro/Empresarial + conectar ERP alimenta o CFO" — até aqui,
-- routes/erp.ts's GET /omie|sap|totvs/contas-receber só devolvia a lista ao vivo pro cliente
-- montar a duplicata em lote (Emitir em lote); o resultado nunca era persistido, então o
-- AI CFO (lib/cashflowForecast.ts) só enxergava recebíveis que já viraram duplicata na
-- Lastro — cego pro resto do faturamento real da empresa. Esta tabela guarda um snapshot de
-- cada busca, dedupe por (cedente, fonte, id externo) via UPSERT, para o forecast somar
-- como "recebíveis externos (fora da Lastro)" — o mesmo dado que já circulava, agora
-- reaproveitado para dar ao CFO uma visão mais completa da empresa (e, de quebra, dar à
-- Lastro um banco de dados real sobre o fluxo de caixa de quem conecta, não só o que decide
-- vender).
CREATE TABLE IF NOT EXISTS erp_receivables (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cedente_id INTEGER NOT NULL REFERENCES users(id),
  fonte TEXT NOT NULL CHECK(fonte IN ('omie', 'sap', 'totvs')),
  external_id TEXT NOT NULL,
  cliente TEXT NOT NULL,
  valor REAL NOT NULL,
  vencimento TEXT NOT NULL,
  fetched_at TEXT NOT NULL DEFAULT now(),
  UNIQUE(cedente_id, fonte, external_id)
);
CREATE INDEX IF NOT EXISTS idx_erp_receivables_cedente ON erp_receivables(cedente_id);
