-- Carrossel de publicidade na landing page: empresas pagantes (papel self-service
-- 'anunciante', ver 0057_anunciante_role.sql) configuram um anúncio (logo, título, texto
-- curto, link), que entra numa fila de aprovação do admin antes de rodar publicamente.
-- UNIQUE(advertiser_id) — uma conta anunciante tem no máximo um anúncio (edita o mesmo em
-- vez de acumular vários), mesmo espírito de "um config por dono" que whitelabelBrand já usa.
CREATE TABLE IF NOT EXISTS advertisements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  advertiser_id INTEGER NOT NULL UNIQUE REFERENCES users(id),
  logo_url TEXT NOT NULL,
  titulo TEXT NOT NULL,
  texto TEXT NOT NULL,
  link_url TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pendente' CHECK(status IN ('pendente', 'aprovado', 'rejeitado')),
  ativo INTEGER NOT NULL DEFAULT 1,
  reject_reason TEXT,
  created_at TEXT NOT NULL DEFAULT now(),
  updated_at TEXT NOT NULL DEFAULT now()
);
-- Consulta pública do carrossel filtra por (status, ativo) a cada visita à landing page —
-- ver routes/public.ts GET /public/advertisements.
CREATE INDEX IF NOT EXISTS idx_advertisements_status_ativo ON advertisements(status, ativo);
