-- Espelho Postgres de 0067_auction_bids.sql — ver os comentários lá.
CREATE TABLE IF NOT EXISTS auction_bids (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  duplicata_id TEXT NOT NULL REFERENCES duplicatas(id),
  bidder_id INTEGER NOT NULL REFERENCES users(id),
  taxa_am REAL NOT NULL,
  preco REAL NOT NULL,
  status TEXT NOT NULL DEFAULT 'ativo' CHECK(status IN ('ativo','vencedor','perdedor','cancelado')),
  created_at TEXT NOT NULL DEFAULT (now())
);
CREATE INDEX IF NOT EXISTS idx_auction_bids_duplicata ON auction_bids(duplicata_id, status);
CREATE INDEX IF NOT EXISTS idx_auction_bids_bidder ON auction_bids(bidder_id, status);

ALTER TABLE duplicatas ADD COLUMN IF NOT EXISTS leilao_fechado_em TEXT;

-- Mesmo backfill do espelho SQLite: duplicata em mercado sem prazo nunca seria fechada.
UPDATE duplicatas SET close_at = to_char(now() + interval '24 hours', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
 WHERE status = 'no_mercado' AND close_at IS NULL;
