import {
  ArrowLeftRight,
  Bot,
  Building2,
  ChartPie,
  ClipboardCheck,
  CodeXml,
  CreditCard,
  Eye,
  FileClock,
  FilePlus,
  Files,
  Gauge,
  Gavel,
  Handshake,
  Landmark,
  LayoutDashboard,
  Megaphone,
  Plug,
  Receipt,
  Repeat,
  Settings,
  ShieldCheck,
  ShoppingBasket,
  Sparkles,
  Store,
  Umbrella,
  UserCheck,
  Wallet,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

// Antes: 21 "ícones" feitos de <div> com border/rotate — 8 tabs eram o mesmo quadradinho e o
// menu virava uma lista de texto indistinguível. Um glifo real por tab (lucide, tree-shaken:
// só os ~30 usados entram no bundle), sempre 16px e `currentColor` pra herdar ativo/inativo.
const ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  marketplace: Store,
  secundario: Repeat,
  cestas: ShoppingBasket,
  automacao: Bot,
  emitir: FilePlus,
  minhas: Files,
  aceite: ClipboardCheck,
  erp: Plug,
  sacado: Building2,
  confirming: Handshake,
  seguradora: Umbrella,
  conta: Wallet,
  historico: FileClock,
  'linha-credito': Landmark,
  'contas-pagar': Receipt,
  'ai-cfo': Sparkles,
  risco: Gauge,
  suitability: UserCheck,
  comparador: ArrowLeftRight,
  compliance: ShieldCheck,
  disputa: Gavel,
  dev: CodeXml,
  publicidade: Megaphone,
  admin: Wrench,
  auditor: Eye,
  receita: ChartPie,
  assinatura: CreditCard,
  perfil: Settings,
};

export function NavIcon({ tab, size = 16 }: { tab: string; size?: number }) {
  const Icon = ICONS[tab] ?? LayoutDashboard;
  return <Icon size={size} strokeWidth={1.75} aria-hidden="true" className="flex-shrink-0" />;
}
