#!/usr/bin/env node
// Translates server/src/db/migrations/*.sql (SQLite) into
// server/src/db/migrations-postgres/*.sql (Postgres) — same filenames, same statement
// order, only the handful of genuinely non-portable bits rewritten. See
// docs/postgres-migration.md for what this does and doesn't prove.
//
// The translation is intentionally narrow: a grep across all 38 migrations at the time
// this was written turned up exactly two non-portable patterns (INTEGER PRIMARY KEY
// AUTOINCREMENT and datetime('now')) — nothing else in the schema (CHECK constraints,
// REFERENCES, CREATE INDEX IF NOT EXISTS, plain ALTER TABLE ADD COLUMN) needs rewriting to
// be valid Postgres DDL. If a future migration introduces something else SQLite-specific,
// this script will still copy it through unchanged and the psql apply step below will fail
// loudly rather than silently producing invalid SQL.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.resolve(__dirname, '../../server/src/db/migrations');
const outDir = path.resolve(__dirname, '../../server/src/db/migrations-postgres');
mkdirSync(outDir, { recursive: true });

function translate(sql) {
  return sql
    // GENERATED BY DEFAULT (not ALWAYS) AS IDENTITY — several migrations rebuild a table
    // (SQLite's "add a CHECK constraint" idiom: create new table, INSERT...SELECT the old
    // rows *with their original id values*, drop old, rename new into place) and explicitly
    // insert into the id column. GENERATED ALWAYS rejects that outright (ERROR: cannot
    // insert a non-DEFAULT value into column "id") unless every such INSERT adds `OVERRIDING
    // SYSTEM VALUE` — real behavior discovered by actually running this against Postgres,
    // not assumed. BY DEFAULT auto-generates only when no value is supplied, matching
    // AUTOINCREMENT's real behavior (which also accepts an explicit id).
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/DEFAULT \(datetime\('now'\)\)/g, 'DEFAULT now()')
    .replace(/datetime\('now'\)/g, 'now()');
}

// Two migrations (0004, 0006) use a SQLite-only idiom to widen a CHECK constraint on
// `users` that has no direct equivalent: SQLite can't ALTER an existing CHECK, so both
// rebuild the whole table (CREATE a shadow table with the new constraint, INSERT...SELECT
// every row across, DROP the original, RENAME the shadow into place). Running that
// rebuild's DROP TABLE against real Postgres fails for a real, useful reason discovered by
// actually attempting it here: Postgres tracks foreign keys as real catalog constraints and
// refuses to drop a table ten other tables still reference (`cannot drop table users
// because other objects depend on it`), whereas SQLite doesn't track FK dependents that
// way, so the same DROP silently succeeds there.
//
// The honest fix isn't a generic rewrite — it's that Postgres never needed the rebuild
// idiom to begin with: `ALTER TABLE ... DROP CONSTRAINT` / `ADD CONSTRAINT ... CHECK` alter
// a CHECK constraint directly, and `ALTER TABLE ... ADD COLUMN` adds the rest, both as
// single real statements with no table copy and no dropped-then-restored FK linkage. The
// resulting Postgres migration is simpler than the SQLite one it replaces, not just a
// syntax port of it. Constraint name `users_role_check` was confirmed against a real
// Postgres 16 instance (Postgres auto-names a single unnamed inline CHECK on column `role`
// exactly that way), not guessed.
const REBUILD_OVERRIDES = {
  '0004_admin_kyb_status.sql': `-- Native Postgres equivalent of the SQLite table-rebuild this migration performs (see
-- REBUILD_OVERRIDES in scripts/postgres/generate-schema.mjs for why the direct syntax
-- port doesn't work and what confirmed this replacement is correct).
ALTER TABLE users ADD COLUMN kyb_status TEXT NOT NULL DEFAULT 'none' CHECK (kyb_status IN ('none','pending','approved','rejected'));
ALTER TABLE users ADD COLUMN kyb_reject_reason TEXT NOT NULL DEFAULT '';

ALTER TABLE users DROP CONSTRAINT users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('investidor','cedente','sacado','admin'));

-- Same backfill the SQLite rebuild's INSERT...SELECT CASE performed for pre-existing rows.
UPDATE users SET kyb_status = CASE
  WHEN role = 'investidor' AND kyb_done = 1 THEN 'approved'
  WHEN role = 'investidor' AND kyb_done = 0 THEN 'none'
  ELSE 'approved'
END;

ALTER TABLE disputes ADD COLUMN resolution TEXT NOT NULL DEFAULT '';
ALTER TABLE disputes ADD COLUMN resolved_by INTEGER REFERENCES users(id);
ALTER TABLE disputes ADD COLUMN resolved_at TEXT;
`,
  '0006_partner_network.sql': `-- Native Postgres equivalent of the SQLite table-rebuild this migration performs (see
-- REBUILD_OVERRIDES in scripts/postgres/generate-schema.mjs).
ALTER TABLE users DROP CONSTRAINT users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('investidor','cedente','sacado','admin','seguradora'));
ALTER TABLE users ADD COLUMN insurer_key TEXT;

ALTER TABLE duplicatas ADD COLUMN sinistro_status TEXT NOT NULL DEFAULT 'none';
ALTER TABLE duplicatas ADD COLUMN sinistro_note TEXT;

CREATE TABLE IF NOT EXISTS api_keys (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  key_hash TEXT NOT NULL UNIQUE,
  key_prefix TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT 'Chave de produção',
  revoked INTEGER NOT NULL DEFAULT 0,
  last_used_at TEXT,
  created_at TEXT NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS webhooks (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  url TEXT NOT NULL,
  event TEXT NOT NULL,
  secret TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_api_keys_user ON api_keys(user_id);
CREATE INDEX IF NOT EXISTS idx_webhooks_user_event ON webhooks(user_id, event);
`,
  // 0045 and 0046 both widen a CHECK constraint the same way 0006 above already does — SQLite
  // needs the whole-table-rebuild dance (see the migration's own comment), Postgres just
  // drops and re-adds the named constraint. These two were hand-written directly into
  // migrations-postgres/ when they were added and never registered here, which meant running
  // this generator would silently regenerate them back to the uglier, auto-translated
  // table-rebuild port instead of leaving the correct native version alone — a real bug this
  // comment exists to prevent from recurring for the next constraint-widening migration.
  '0045_auditor_role.sql': `ALTER TABLE users DROP CONSTRAINT users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('investidor','cedente','sacado','admin','seguradora','auditor'));
`,
  '0046_bank_statement_reconciliation.sql': `ALTER TABLE reconciliation_flags DROP CONSTRAINT reconciliation_flags_tipo_check;
ALTER TABLE reconciliation_flags ADD CONSTRAINT reconciliation_flags_tipo_check CHECK (tipo IN ('pix', 'boleto', 'ted', 'extrato_bancario'));
`,
};

const files = readdirSync(srcDir).filter((f) => f.endsWith('.sql')).sort();
let translatedFiles = 0;
let overriddenFiles = 0;
for (const file of files) {
  const original = readFileSync(path.join(srcDir, file), 'utf8');
  const translated = REBUILD_OVERRIDES[file] ?? translate(original);
  if (REBUILD_OVERRIDES[file]) overriddenFiles++;
  writeFileSync(path.join(outDir, file), translated);
  translatedFiles++;
}

console.log(`Translated ${translatedFiles} migration(s) → ${path.relative(process.cwd(), outDir)}`);
if (overriddenFiles > 0) console.log(`(${overriddenFiles} file(s) hand-translated to native Postgres DDL — see REBUILD_OVERRIDES)`);
